version: '3.9'

services:
  db:
    image: mongo:7
    container_name: db-container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  db-server:
    build: .
    image: db-server
    container_name: db-server-container
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/BoundingBoxers

volumes:
  mongo_data: